### PR TITLE
Add the link of Chinese version of code reviewer's guide

### PR DESCRIPTION
**Pull request by life1347**
I tried to translate the code reviewer's guide into the Chinese version. Since the "Issues" tab is not visible, I created this PR to see if it's possible to add links for different language translation. 
If it's not a good idea, let me know, I will close the PR.

And, thanks for creating this ***awesome*** repo.

### CODE REVIEW

**Comment by life1347** [comment]
Thanks for your quick response. I agree with the points you list. I will close this one and maintain a fork as your suggestion.

**Comment by pauloedurezende** [comment]
@limakzi So what would you recommend to others who want to translate to this repository? Make a fork, perform the translation and then open a pull request with these changes for this project. Or make a fork of this project, perform the translation, configure GitHub Pages and reference the translation in this project?

**Comment by mkanat** [comment]
While I appreciate the participation of @limakzi in this thread, he is not a reviewer or approver on this project. Let's leave this open for @adambender to review.

**Comment by limakzi** [comment]
@mkanat This is something I wanted to write down after reading @pauloedurenze comment. 
I cannot be an approver and I am not maintainer of this project. This is just my and only my own suggestion.

**Comment by adambender** [comment]
Hey all, new maintainer here. Im thrilled about having a Chinese version of the guide however, I need to find someone inside Google who can confirm the quality of the translation for me. Im going to let this PR stay open until I am able to do so.

**Comment by lightClouds917** [comment]
The Chinese version is a good idea. Many Chinese developers need this and can even offer multilingual versions.

**Comment by rootsongjc** [comment]
I have translated one https://jimmysong.io/eng-practices/

**Comment by lightClouds917** [comment]
> I have translated one https://jimmysong.io/eng-practices/

Thank you for your contribution.

**Comment by life1347** [comment]
@rootsongjc  How about we merge two different Chinese translation versions into one? 

I can be in charge of the traditional Chinese version (replace some phrases that more often used in Taiwan.) In this way, we can review the docs and polish the final result to make sure that the output is close to the original one.

What do you think?

**Comment by rootsongjc** [comment]
@life1347 Based on which repo? Or create a new one?

**Comment by life1347** [comment]
I just created an org `https://github.com/eng-practices` to host the repo. Since your repo structure is more close to the original one, how about you open a PR to this [repo](https://github.com/eng-practices/eng-practices) and then I base on the work to do the translation?

We can create separate directories for different languages like
```
.
├── LICENSE
├── README.md
├── _config.yml
├── review
├── zh-cn
│   └── review
└── zh-tw
    └── review
``` 

I'm willing to add anyone who is interesting in helping to maintain the repo.
@adambender I'm thinking to add you to the org as well, let me know if it's a good idea. Thanks

**Comment by rootsongjc** [comment]
@life1347 OK, I'll take this.

**Comment by ninachen** [comment]
Hi there,
Apologies for the very long delay. I am the new owner of eng-practices and doing a review of open requests.

Thank you for making this huge contribution! We would be happy to incorporate it; I assume you are still interested in submitting this change.

If so, I will assign some Googler reviewers to the PR to do a final review: does that sound good to you?

**Comment by life1347** [comment]
Hi @ninachen yes, that sounds good! 

@rootsongjc and I have worked on the [simplified Chinese version](https://github.com/eng-practices/eng-practices). I can close this one and open a new PR instead. Do you have any suggestions for how to organize the repo structure so that we can put the translated version into the right place? 

Let me know if there is anything I can do to make the review process more smooth. And I would love to help to translate it into the traditional Chinese version as well.

**Comment by ninachen** [comment]
Sounds good! Your Googler reviewers will be @poponybing and @gavinbird.

> Do you have any suggestions for how to organize the repo structure so that we can put the translated version into the right place?

Not at this time. Let's focus on the content first, and I and the other owners can figure out where the content should live separately -- no need to block the content review on figuring out the file organization. :)

**Comment by life1347** [comment]
Close this one. See #20 instead.

**Pull request closed without merging**
