### PR TITLE
Update looking-for.md

### PR DESCRIPTION
**Pull request by oscarmandley**
I found this
https://google.github.io/eng-practices/review/reviewer/looking-for.html
and was confused about what CL stood for.

### CODE REVIEW

**Comment by oscarmandley** [comment]
@googlebot I signed it!

**Comment by ninachen** [comment]
Hi, thanks for the PR. We're planning to address the widespread use of "CL" within the content with a fix to issue #22, which will involve a tooling fix on our side. (Apologies for the slow movement on the issue; 2020 has been...something.)

**Review by ProxyHydra — COMMENTED** [review]
Reviewed. Text is grammatically accurate.

**Comment by JanHadari** [comment]
Děkuji pěkně

**Pull request closed without merging**
