### PR TITLE
Add VC and TL to Terminology

### PR DESCRIPTION
**Pull request by chmac**
I found these acronyms here https://google.github.io/eng-practices/review/reviewer/standard.html and couldn't find an explanation of what they  mean. Unfortunately I don't know what VC means, so I was not able to suggest a definition.

Hopefully somebody can correct these terms and then merge (or create a new PR if you prefer).

### CODE REVIEW

**Comment by shuuji3** [comment]
Assuming by the context, I think "VC" stands for "Video Chat" and "TL" for "Technical Lead" (a position in Google; Ref. [Google Cloud - Google Careers](https://www.google.com/intl/es_ALL/about/careers/cloud/)). But the right answer would be presented by Googler :)

**Comment by chmac** [comment]
Oh yeah, good idea. Maybe it would be better to replace those acronyms with their full versions in place. That might make for a more readable document...

**Comment by david942j** [comment]
VC for Video Chat and TL for Team Lead.

**Comment by mkanat** [comment]
VC = Videoconference
TL = Tech Lead

**Comment by adambender** [comment]
The terms TL and VC are in *very* common use internally (which is why we probably didn't expand them originally). I think adding an update to the front page is fine. I suspect replacing the acronyms will actually cause a minor annoyance internally so Id prefer to leave most of the doc as is.

**Comment by chmac** [comment]
I haven't looked into what's required for the CLA process. Anybody else who has already done that want to submit a PR adding these definitions and then I can close this one?

**Comment by adambender** [comment]
I may have found a way to automatically convert these as we ship them out. I'll try to tackle it in the next few weeks.

**Comment by guettli** [comment]
Why not add a glossary and explain the acronyms? What speaks agains a glossary.

**Comment by adambender** [comment]
I have gone ahead and updated the upstream documents internally and they will now be publishing with the acronyms expanded. There should no longer be a need to add them to the glossary so I am going to close this PR.

Apologies for the delay in responding.

**Pull request closed without merging**
