### PR TITLE
adding term

### PR DESCRIPTION
**Pull request by closb**
Added NIT for clarity, although not necessarily an internal term. I believe it's needed.

### CODE REVIEW

**Review by closb — COMMENTED** [review]
completed CLA

**Comment by shuuji3** [comment]
As you wrote, I think "Nit" is sometimes used in other projects. If we need to add, so it should be the distinguish section.

This is itself nit but I only see the word in the form "Nit", not "NIT".

Also, I found the exact same explanation in Mozilla Wiki: https://wiki.mozilla.org/Bugzilla:Review#:~:text=request%20review%20again.-,Sometimes%20the%20reviewer%20will%20prefix%20his%20comments%20with%20%22Nit%3A%22.%20This%20means%20that%20he%27s%20just%20%22nitpicking%22%2D%2Dyou%20don%27t%20have%20to%20fix%20these%20points%2C%20but%20we%27d%20like%20you%20to.,-If%20you%20disagree, which is licensed as CC-BY-SA 3.0 https://wiki.mozilla.org/MozillaWiki:Copyrights, meaning it requires attribution.

**Comment by mkanat** [comment]
Funny story: I also wrote that text on Bugzilla:Review. :)

**Comment by closb** [comment]
I thought of a different section but didn't see too many references to justify it, maybe a tooltip? That said, I used NIT to match the format of other words.

**Pull request closed without merging**
